version: '3.9'

services:
  bind:
    image: sameersbn/bind:9.16.1-20200524
    container_name: bind-dns
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
    environment:
      - WEBMIN_ENABLED=false
    restart: always
    volumes:
      - ./bind-data:/data
    networks:
      cdn:
        ipv4_address: 172.20.0.2
        
  lb1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load_balancer_1
    volumes:
      - ./UA/lb1/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.3
    dns:
      - 172.20.0.2

  lb2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load_balancer_2
    volumes:
      - ./EUROPE/lb2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.4
    dns:
      - 172.20.0.2
        
  nginx1:
    image: nginx:alpine
    container_name: nginx_server_1
    volumes:
      - ./UA/images:/usr/share/nginx/html
      - ./UA/server1-2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.5
    dns:
      - 172.20.0.2

  nginx2:
    image: nginx:alpine
    container_name: nginx_server_2
    volumes:
      - ./UA/images:/usr/share/nginx/html
      - ./UA/server1-2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.6
    dns:
      - 172.20.0.2
        
  nginx3:
    image: nginx:alpine
    container_name: nginx_server_3
    volumes:
      - ./EUROPE/images:/usr/share/nginx/html
      - ./EUROPE/server3-4/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.7
    dns:
      - 172.20.0.2

  nginx4:
    image: nginx:alpine
    container_name: nginx_server_4
    volumes:
      - ./EUROPE/images:/usr/share/nginx/html
      - ./EUROPE/server3-4/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.8
    dns:
      - 172.20.0.2
  
  nginx_client_ua:
    image: nginx:alpine
    container_name: nginx_client_ua
    volumes:
      - ./client-ua/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.9
    ports:
      - "8080:80"
    dns:
      - 172.20.0.2
  
  nginx_client:
    image: nginx:alpine
    container_name: nginx_client
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    networks:
      cdn:
        ipv4_address: 172.20.0.10
    ports:
      - "8081:81"
    dns:
      - 172.20.0.2

networks:
  cdn:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
